name: ESTimate Automation (ESTA) Jira Sync

description: Custom GitHub Action for analyzing the complexity added to a repository through static analysis and uploading it to Jira

inputs:
  working_directory:
    description: target directory for analysis
    default: "."
  blob_storage:
    description: supports S3 bucket only
  language:
    description: language to compute circuit rank complexity for - supports js and ts
  context:
    description: GH action context

outputs:
  card-url:
    description: Link to card referenced in PR

runs:
  using: "node16"
  main: "src/esta-action/index.js"
  post-if: "success()"
