name: ESTimate Automation (ESTA) Jira Sync

description: Custom GitHub Action for analyzing the complexity added to a repository through static analysis and uploading it to Jira

# inputs:
#   jira-token:
#     description: PAT for service account at Jira, must have read/write access
#     required: true
#   github-token:
#     description: GITHUB_TOKEN secret required for auth into GH APIs
#     required: true

outputs:
  card-url:
    description: Link to card referenced in PR

runs:
  using: "node16"
  main: "dist/index.js"
  post-if: "success()"
