name: ESTimate Automation (está)

description: está takes a temporary state in software construction by performing static analysis on the codebase and uploads it to S3 for future analysis

inputs:
  working_directory:
    description: target directory for analysis
  blob_storage:
    description: supports S3 bucket only
  language:
    description: language to compute circuit rank complexity for - supports js and ts
  sha:
    description: SHA for commit
  actor:
    description: PR author

outputs:
  card-url:
    description: Link to card referenced in PR

runs:
  using: "node16"
  main: "src/esta-action/index.js"
  post-if: "success()"
