name: Test Code
on:
  push:
    branches:
      - main

jobs:
  # unit tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --immutable
      - run: yarn test
