name: Test Action
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - v*

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
      - uses: ./
        with:
          sha: ${{ github.sha }}
          actor: ${{ github.actor }}
          working_directory: src
          ecma_script_target: ES2015
