name: Test Action
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - v*

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all

      - name: Test Action
        id: test-action
        uses: ./
        with:
          working_directory: src
          ecma_script_target: ES2021
          event: ${{ toJson(github.event) }}

      - name: Print Report
        shell: bash
        run: cat ${{ steps.test-action.outputs.export_filename }}
